# Generated by Django 4.1.4 on 2022-12-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user_profile',
            new_name='user',
        ),
    ]
